/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import java.util.List;
import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author Sarifa Nuha AJ / 24060124130082
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    private MysqlMahasiswaService mahasiswaService;
    
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        mahasiswaService = new MysqlMahasiswaService();
        jListID.setModel(new DefaultListModel<>());
        jList1.setModel(new DefaultListModel<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jLabelID = new javax.swing.JLabel();
        jLabelListNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddAll = new javax.swing.JButton();
        jLabelInputNama = new javax.swing.JLabel();
        jTextFieldAdd = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldUpdateId = new javax.swing.JTextField();
        jTextFieldDeleteId = new javax.swing.JTextField();
        jTextFieldUpdateName = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldDeleteName = new javax.swing.JTextField();
        jButtonResetIndex = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListID);

        jLabelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelID.setText("ID");

        jLabelListNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelListNama.setText("NAMA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Kelola Data Mahasiswa");

        jButtonAddAll.setText("Ambil Semua Data");
        jButtonAddAll.addActionListener(this::jButtonAddAllActionPerformed);

        jLabelInputNama.setText("Nama:");

        jTextFieldAdd.addActionListener(this::jTextFieldAddActionPerformed);

        jButtonAdd.setText("Tambahkan");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jTextFieldUpdateId.addActionListener(this::jTextFieldUpdateIdActionPerformed);

        jTextFieldDeleteId.addActionListener(this::jTextFieldDeleteIdActionPerformed);

        jButtonUpdate.setText("Edit");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonResetIndex.setText("Reset Indeks");
        jButtonResetIndex.addActionListener(this::jButtonResetIndexActionPerformed);

        jLabel2.setText("Indeks di reset ke 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListNama))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddAll)
                            .addComponent(jLabel1)
                            .addComponent(jLabelInputNama))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDeleteName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldUpdateName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonResetIndex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(jTextFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdd))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jLabelListNama)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddAll)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInputNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndex)
                            .addComponent(jLabel2))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddActionPerformed

    private void jTextFieldUpdateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateIdActionPerformed

    private void jTextFieldDeleteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeleteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeleteIdActionPerformed

    private void jButtonAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAllActionPerformed
        // Mengambil semua data dari database
        List<Mahasiswa> daftarMahasiswa = mahasiswaService.getAll();
        
        // Membuat model untuk list
        DefaultListModel<String> modelID = new DefaultListModel<>();
        DefaultListModel<String> modelNama = new DefaultListModel<>();
        
        // Mengisi model dengan data dari database
        if (daftarMahasiswa.isEmpty()) {
            modelID.addElement("Tidak ada data");
            modelNama.addElement("Tidak ada data");
        } else {
            for (Mahasiswa mhs : daftarMahasiswa) {
                modelID.addElement(String.valueOf(mhs.getId()));
                modelNama.addElement(mhs.getNama());
            }
        }
        
        // Set model ke JList
        jListID.setModel(modelID);
        jList1.setModel(modelNama);
    }//GEN-LAST:event_jButtonAddAllActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // Mengambil input nama dari text field
        String nama = jTextFieldAdd.getText().trim();
        
        // Validasi input tidak boleh kosong
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nama tidak boleh kosong!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Cek apakah tabel kosong untuk menentukan ID
        int newId = 1;
        if (!mahasiswaService.isEmpty()) {
            List<Mahasiswa> allMhs = mahasiswaService.getAll();
            int maxId = 0;
            for (Mahasiswa mhs : allMhs) {
                if (mhs.getId() > maxId) {
                    maxId = mhs.getId();
                }
            }
            newId = maxId + 1;
        }
        
        // Membuat objek mahasiswa baru
        Mahasiswa mhsBaru = mahasiswaService.makeMhsObject();
        mhsBaru.setId(newId);
        mhsBaru.setNama(nama);
        
        // Menambahkan ke database
        mahasiswaService.add(mhsBaru);
        
        // Mengosongkan text field
        jTextFieldAdd.setText("");
        
        // Refresh tampilan data
        jButtonAddAllActionPerformed(evt);

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonResetIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndexActionPerformed
         // Cek apakah tabel kosong
        if (mahasiswaService.isEmpty()) {
            mahasiswaService.indexReset();
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Indeks berhasil direset ke 1!", 
                "Sukses", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Tabel harus kosong untuk mereset indeks!\nHapus semua data terlebih dahulu.", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonResetIndexActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // Mengambil input ID dan nama baru
        String idStr = jTextFieldUpdateId.getText().trim();
        String namaBaru = jTextFieldUpdateName.getText().trim();
        
        // Validasi input
        if (idStr.isEmpty() || namaBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "ID dan Nama tidak boleh kosong!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(idStr);
            
            // Cek apakah ID ada
            Mahasiswa mhsExist = mahasiswaService.getById(id);
            if (mhsExist == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "ID " + id + " tidak ditemukan!", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Update data
            mhsExist.setNama(namaBaru);
            mahasiswaService.update(mhsExist);
            
            // Mengosongkan text field
            jTextFieldUpdateId.setText("");
            jTextFieldUpdateName.setText("");
            
            // Refresh tampilan data
            jButtonAddAllActionPerformed(evt);
            
            // Menampilkan pesan sukses
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Data berhasil diupdate!", 
                "Sukses", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "ID harus berupa angka!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // Mengambil input ID
        String idStr = jTextFieldDeleteId.getText().trim();
        
        // Validasi input
        if (idStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "ID tidak boleh kosong!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(idStr);
            
            // Cek apakah ID ada
            Mahasiswa mhsExist = mahasiswaService.getById(id);
            if (mhsExist == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "ID " + id + " tidak ditemukan!", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Konfirmasi penghapusan
            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah yakin ingin menghapus data dengan ID " + id + "?\nNama: " + mhsExist.getNama(),
                "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                // Hapus data
                mahasiswaService.delete(id);
                
                // Mengosongkan text field
                jTextFieldDeleteId.setText("");
                jTextFieldDeleteName.setText("");
                
                // Refresh tampilan data
                jButtonAddAllActionPerformed(evt);
                
                // Menampilkan pesan sukses
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Data berhasil dihapus!", 
                    "Sukses", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
                
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "ID harus berupa angka!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonResetIndex;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInputNama;
    private javax.swing.JLabel jLabelListNama;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldAdd;
    private javax.swing.JTextField jTextFieldDeleteId;
    private javax.swing.JTextField jTextFieldDeleteName;
    private javax.swing.JTextField jTextFieldUpdateId;
    private javax.swing.JTextField jTextFieldUpdateName;
    // End of variables declaration//GEN-END:variables
}
